# Generated by Django 5.1.3 on 2024-11-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initial_params', models.JSONField()),
                ('final_measurements', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='myapp.experimentsession')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_tab', models.CharField(max_length=20)),
                ('elastic_state', models.JSONField()),
                ('inelastic_state', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='myapp.experimentsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
